name: web-audio-hs
version: "0.0.0"

library:
  source-dirs: src

executables:
  web-audio-hs-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - web-audio-hs

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - colour >=2.3.6
  - dlist >= 1.0
  - fgl >= 5.8.1.1
  - polyparse >= 1.13
  - temporary >= 1.3
  - wl-pprint-text >= 1.2.0.2
  - graphviz >= 2999.20.1.0
  - text >= 1.2.5.0
  - filepath >= 1.4.2.2
  - containers >= 0.6.5.1
  - aeson >= 2.2.0.0
  - bytestring >= 0.11.4.0
